### PR TITLE
Fixing nii -> bo -> nii conversion; dropping support for python 2.7

### PR DESCRIPTION
**Pull request by tmuntianu**
In order to get nii -> bo -> nii and bo -> nii -> bo conversions both working, added a `from .bo` flag in the Nifti header's `descrip` to be able to handle both cases. Am still not sure why this is necessary, since all of the affine transformations check out.

Also dropped support for 2.7 in both the readme and the Travis tests; skipping all GPU tests when there is no GPU or `CuPy` available.

### CODE REVIEW

**Comment by lucywowen** [comment]
Looks good to me!

**Comment by tmuntianu** [comment]
@jeremymanning can we merge this? would be good to get a new pip release going too, esp before cosyne

**Comment by jeremymanning** [comment]
@tmuntianu I'm so sorry i missed this-- @lucywowen can you check it over also?  Seems good to me...

**Comment by jeremymanning** [comment]
* merged since it looks like Lucy has already signed off.

**Comment by jeremymanning** [comment]
should we update pip?

**Pull request merged**
